### ISSUE TITLE
Overrides existing component when the same name chosen for the new component

### ISSUE THREAD

**Issue by maciej-skurznica** [coolassassin/reactcci#11]
I need to be very cautious when choosing components names because when I chose the same name as any existing component in the desired folder it will create new comp and override the existing one. Then all the code is gone.

**Comment by coolassassin** [comment]
> 

Hello!

Good point. I will add confirmation for that case, then.
Anyway, while you use git, it is easy to make reverse code. And IDE also can help you with that.

But, yeah. I will try to cover this. Probably it will be an optional feature, because it could be not good for backward compatibility.

**Comment by coolassassin** [comment]
@mps92 As I promised, I have add new flag.
Name is `checkExistenceOnCreate`

You need to upload fresh version of package.
Then open your `rcci.config.js` file and fix like that:
```js
module.exports = {
  checkExistenceOnCreate: true,
  [...your config]
}
```

Hope you enjoy. Happy templating :)

**Comment by maciej-skurznica** [comment]
Men it works! 🍺🙏
